# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/zentao?useUnicode=true&characterEncoding=utf-8
    username: jayang
    password: jayang880706
security:
  ignoring: "/static/**/*, /druid/**/**, /login.ftl,/login.ftl1, /webjars/**/*, /images/**/*,/oauth/token,/oauth/authorize" 
  intercept: "/**/*.jsp, /**/*.html, /**/*.ftl"
  successUrl: "/index.ftl"
  logoutSuccessUrl: "/login.ftl"
  user:
    name: root
    password: 1234
  oauth2:
    client:
      clientId: resource1
      clientSecret: secret
      userAuthorizationUri: http://localhost:8083/oauth/authorize
#     // grant-type: password
      scope: app
      access-token-uri: http://localhost:8083/oauth/token
    resource:
      userInfoUri: http://localhost:8083/oauthhello
      filter-order: 3
    authorization:
      check-token-access: http://localhost:8083/oauth/check_token
  basic:
    enabled: true
management:
  security:
    enable: true
server:
  port: 8083